"use client"

import { Badge } from "@/components/ui/badge"
import { TrendingUp, Shield, Scale, Activity, Zap, Crown, Medal, Award } from "lucide-react"

const rankingCategories = [
  {
    icon: Activity,
    title: "Most Stable Businesses",
    description: "Lowest cashflow variance over 12 months",
    companies: [
      { name: "Mombasa Tech Hub", score: 97, change: "+2" },
      { name: "Kofi Farms Ltd", score: 94, change: "+1" },
      { name: "Kampala Fresh Foods", score: 93, change: "0" },
    ],
  },
  {
    icon: TrendingUp,
    title: "Strongest Verified Growth",
    description: "Highest encrypted growth rate",
    companies: [
      { name: "Lagos Logistics Co", score: 89, change: "+5" },
      { name: "Dakar Solar Energy", score: 91, change: "+3" },
      { name: "Abidjan Textiles", score: 86, change: "+2" },
    ],
  },
  {
    icon: Shield,
    title: "Best Governance Proofs",
    description: "Highest governance and compliance scores",
    companies: [
      { name: "Mombasa Tech Hub", score: 98, change: "+1" },
      { name: "Dakar Solar Energy", score: 95, change: "+2" },
      { name: "Kofi Farms Ltd", score: 92, change: "0" },
    ],
  },
  {
    icon: Scale,
    title: "Most Consistent Cashflow",
    description: "Best month-over-month consistency",
    companies: [
      { name: "Kampala Fresh Foods", score: 96, change: "+1" },
      { name: "Kofi Farms Ltd", score: 94, change: "+2" },
      { name: "Mombasa Tech Hub", score: 93, change: "0" },
    ],
  },
  {
    icon: Zap,
    title: "Highest Efficiency",
    description: "Best operational efficiency metrics",
    companies: [
      { name: "Lagos Logistics Co", score: 91, change: "+3" },
      { name: "Mombasa Tech Hub", score: 90, change: "+1" },
      { name: "Dakar Solar Energy", score: 88, change: "+2" },
    ],
  },
]

const rankIcons = [Crown, Medal, Award]

export function TrustRankings() {
  return (
    <section id="rankings" className="py-20 bg-gradient-to-b from-black to-zinc-950">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        <div className="text-center mb-16">
          <Badge className="mb-4 bg-white/5 text-white/80 border-white/10 hover:bg-white/10">Trust Rankings</Badge>
          <h2 className="text-3xl lg:text-4xl font-bold text-white mb-4 tracking-tight">
            AI-Generated{" "}
            <span className="bg-gradient-to-r from-red-400 to-red-600 bg-clip-text text-transparent">Trust Index</span>
          </h2>
          <p className="text-lg text-white/60 max-w-2xl mx-auto">
            Rankings generated by cryptographically verified analysis, not stories. Pure mathematical truth.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {rankingCategories.map((category, index) => (
            <div
              key={index}
              className="bg-white/[0.02] border border-white/10 rounded-2xl p-6 hover:bg-white/[0.04] hover:border-white/20 transition-all duration-300"
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-red-500/10 to-red-600/10 flex items-center justify-center border border-red-500/20">
                  <category.icon className="w-5 h-5 text-red-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-white text-sm">{category.title}</h3>
                  <p className="text-xs text-white/40">{category.description}</p>
                </div>
              </div>

              <div className="space-y-3">
                {category.companies.map((company, i) => {
                  const RankIcon = rankIcons[i]
                  return (
                    <div
                      key={i}
                      className="flex items-center justify-between p-3 bg-white/[0.02] rounded-lg border border-white/5 hover:border-white/10 transition-colors"
                    >
                      <div className="flex items-center gap-3">
                        <div
                          className={`w-6 h-6 rounded-full flex items-center justify-center ${
                            i === 0
                              ? "bg-gradient-to-br from-yellow-400 to-yellow-600"
                              : i === 1
                                ? "bg-gradient-to-br from-gray-300 to-gray-500"
                                : "bg-gradient-to-br from-amber-600 to-amber-800"
                          }`}
                        >
                          <RankIcon className="w-3 h-3 text-white" />
                        </div>
                        <span className="text-sm text-white/80">{company.name}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-semibold text-white">{company.score}</span>
                        <span
                          className={`text-xs ${company.change.startsWith("+") ? "text-green-400" : "text-white/40"}`}
                        >
                          {company.change}
                        </span>
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          ))}

          {/* CTA Card */}
          <div className="bg-gradient-to-br from-red-500/10 to-red-600/5 border border-red-500/20 rounded-2xl p-6 flex flex-col justify-center">
            <div className="text-center">
              <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-red-500 to-red-600 flex items-center justify-center mx-auto mb-4">
                <TrendingUp className="w-7 h-7 text-white" />
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">Get Your Trust Score</h3>
              <p className="text-sm text-white/50 mb-4">
                Connect your data and receive your AI-generated trust ranking in minutes
              </p>
              <Badge className="bg-white/10 text-white border-white/20 hover:bg-white/20 cursor-pointer">
                Apply for Listing
              </Badge>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
