"use client"

import { useState } from "react"
import { ChevronDown, HelpCircle, Shield, Zap, Globe, CreditCard, Users, TrendingUp } from "lucide-react"
import { useI18n } from "@/lib/i18n"

const faqData = {
  en: [
    {
      icon: Zap,
      q: "What is Fvundi and how does it work?",
      a: "Fvundi is an AI-powered financial intelligence platform built for African and emerging-market SMEs. Simply connect your data sources — invoices, mobile money, spreadsheets — and our AI instantly generates professional financial reports, cash flow insights, and investor-ready documents.",
    },
    {
      icon: Shield,
      q: "How does Fvundi keep my financial data private?",
      a: "Your privacy is absolute. We use homomorphic encryption and zero-knowledge proofs, which means our AI analyzes your data without ever seeing the actual numbers. Your information is encrypted on your device and stays encrypted throughout all processing.",
    },
    {
      icon: Globe,
      q: "Which countries and currencies does Fvundi support?",
      a: "We currently support Nigeria, Kenya, South Africa, Ghana, Egypt, Morocco, Tanzania, Rwanda, Côte d'Ivoire, and more. We handle local currencies, mobile money platforms (M-Pesa, Orange Money, MTN), and are expanding rapidly across Africa.",
    },
    {
      icon: CreditCard,
      q: "Is there a free plan available?",
      a: "Yes! Our Starter plan is completely free and includes core features like basic financial reports, 1 pitch deck, and 5 investor interactions monthly. Upgrade anytime to unlock advanced analytics and unlimited access.",
    },
    {
      icon: TrendingUp,
      q: "What is the Trust Score and why does it matter?",
      a: "The Trust Score is a verified rating generated by our AI using encrypted financial data. It proves your business stability, solvency, and growth — all mathematically verified — helping you build credibility with investors without exposing sensitive details.",
    },
    {
      icon: Users,
      q: "Can Fvundi help me raise funding?",
      a: "Absolutely. Fvundi generates investor-ready documents, verified Trust Scores, and ESG reports. Our marketplace connects you directly with investors who can see your verified credentials without accessing your raw financial data.",
    },
    {
      icon: Zap,
      q: "How fast are reports generated?",
      a: "Most reports are ready in seconds. Balance sheets, cash flow projections, risk assessments, and business valuations are generated near-instantly once your data sources are connected.",
    },
    {
      icon: Shield,
      q: "What data sources can I connect?",
      a: "Fvundi accepts photos of receipts and invoices (our AI extracts the data), mobile money accounts, bank feeds, Excel/CSV files, and integrations with popular accounting software. Everything is automatically categorized.",
    },
    {
      icon: Globe,
      q: "How does the crowdfunding marketplace work?",
      a: "SMEs create encrypted profiles with verified Trust Scores. Investors browse companies, view cryptographic proofs of financial health, and fund opportunities — all without either party exposing sensitive information. Trust becomes automatic and mathematical.",
    },
    {
      icon: CreditCard,
      q: "What payment methods are accepted?",
      a: "We accept all major credit cards, mobile money (M-Pesa, Orange Money, MTN Mobile Money), and bank transfers for annual plans. Payments are processed securely through encrypted channels.",
    },
  ],
  fr: [
    {
      icon: Zap,
      q: "Qu'est-ce que Fvundi et comment ça fonctionne ?",
      a: "Fvundi est une plateforme d'intelligence financière alimentée par l'IA, conçue pour les PME africaines et des marchés émergents. Connectez simplement vos sources de données — factures, mobile money, tableurs — et notre IA génère instantanément des rapports financiers professionnels.",
    },
    {
      icon: Shield,
      q: "Comment Fvundi protège-t-il mes données financières ?",
      a: "Votre confidentialité est absolue. Nous utilisons le chiffrement homomorphe et les preuves à divulgation nulle, ce qui signifie que notre IA analyse vos données sans jamais voir les chiffres réels. Vos informations sont chiffrées sur votre appareil.",
    },
    {
      icon: Globe,
      q: "Quels pays et devises Fvundi prend-il en charge ?",
      a: "Nous supportons actuellement le Nigeria, le Kenya, l'Afrique du Sud, le Ghana, l'Égypte, le Maroc, la Tanzanie, le Rwanda, la Côte d'Ivoire et plus encore. Nous gérons les devises locales et les plateformes mobile money.",
    },
    {
      icon: CreditCard,
      q: "Y a-t-il un plan gratuit disponible ?",
      a: "Oui ! Notre plan Starter est entièrement gratuit et comprend les fonctionnalités de base comme les rapports financiers, 1 pitch deck et 5 interactions avec des investisseurs par mois. Passez à un plan supérieur quand vous voulez.",
    },
    {
      icon: TrendingUp,
      q: "Qu'est-ce que le Trust Score et pourquoi est-il important ?",
      a: "Le Trust Score est une note vérifiée générée par notre IA utilisant des données financières chiffrées. Il prouve la stabilité, la solvabilité et la croissance de votre entreprise — le tout vérifié mathématiquement.",
    },
    {
      icon: Users,
      q: "Fvundi peut-il m'aider à lever des fonds ?",
      a: "Absolument. Fvundi génère des documents prêts pour les investisseurs, des Trust Scores vérifiés et des rapports ESG. Notre marketplace vous connecte directement avec des investisseurs.",
    },
    {
      icon: Zap,
      q: "À quelle vitesse les rapports sont-ils générés ?",
      a: "La plupart des rapports sont prêts en quelques secondes. Bilans, projections de trésorerie, évaluations de risques et valorisations d'entreprise sont générés quasi instantanément.",
    },
    {
      icon: Shield,
      q: "Quelles sources de données puis-je connecter ?",
      a: "Fvundi accepte les photos de reçus et factures, les comptes mobile money, les flux bancaires, les fichiers Excel/CSV et les intégrations avec les logiciels comptables populaires.",
    },
    {
      icon: Globe,
      q: "Comment fonctionne la marketplace de crowdfunding ?",
      a: "Les PME créent des profils chiffrés avec des Trust Scores vérifiés. Les investisseurs parcourent les entreprises et voient des preuves cryptographiques de santé financière — sans exposer d'informations sensibles.",
    },
    {
      icon: CreditCard,
      q: "Quels modes de paiement sont acceptés ?",
      a: "Nous acceptons toutes les principales cartes de crédit, le mobile money (M-Pesa, Orange Money, MTN) et les virements bancaires pour les plans annuels.",
    },
  ],
}

export function FAQSection() {
  const [openItems, setOpenItems] = useState<number[]>([0]) // First item open by default
  const { t, locale } = useI18n()

  const faqs = faqData[locale]

  const toggleItem = (index: number) => {
    setOpenItems((prev) => (prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]))
  }

  return (
    <section className="py-24 lg:py-32 bg-background relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-1/4 left-0 w-96 h-96 bg-gradient-to-br from-red-500/5 to-transparent rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-0 w-96 h-96 bg-gradient-to-bl from-red-500/5 to-transparent rounded-full blur-3xl" />
      </div>

      <div className="max-w-4xl mx-auto px-6 lg:px-8 relative z-10">
        {/* Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-red-500/20 bg-red-500/5 mb-6">
            <HelpCircle className="w-4 h-4 text-red-400" />
            <span className="text-sm text-red-400 font-medium">FAQ</span>
          </div>
          <h2 className="text-3xl lg:text-5xl font-bold text-foreground mb-4 tracking-tight">
            Questions?{" "}
            <span className="bg-gradient-to-r from-red-500 to-red-400 bg-clip-text text-transparent">
              We have answers.
            </span>
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Everything you need to know about Fvundi. Can't find what you're looking for? Reach out to our team.
          </p>
        </div>

        {/* FAQ Accordion */}
        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const Icon = faq.icon
            const isOpen = openItems.includes(index)

            return (
              <div
                key={index}
                className={`rounded-2xl border transition-all duration-300 ${
                  isOpen
                    ? "border-red-500/30 bg-gradient-to-br from-red-500/5 to-transparent shadow-lg shadow-red-500/5"
                    : "border-border bg-card/50 hover:border-border/80"
                } backdrop-blur-sm overflow-hidden`}
              >
                <button
                  onClick={() => toggleItem(index)}
                  className="w-full flex items-center gap-4 p-5 text-left group"
                >
                  {/* Icon */}
                  <div
                    className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 transition-all duration-300 ${
                      isOpen
                        ? "bg-gradient-to-br from-red-500 to-red-600 text-white"
                        : "bg-secondary/50 text-muted-foreground group-hover:text-foreground"
                    }`}
                  >
                    <Icon className="w-5 h-5" />
                  </div>

                  {/* Question */}
                  <span
                    className={`font-medium flex-1 pr-4 transition-colors duration-300 ${
                      isOpen ? "text-foreground" : "text-foreground/80"
                    }`}
                  >
                    {faq.q}
                  </span>

                  {/* Chevron */}
                  <div
                    className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 transition-all duration-300 ${
                      isOpen ? "bg-red-500/20 rotate-180" : "bg-secondary/50"
                    }`}
                  >
                    <ChevronDown
                      className={`w-4 h-4 transition-colors duration-300 ${
                        isOpen ? "text-red-400" : "text-muted-foreground"
                      }`}
                    />
                  </div>
                </button>

                {/* Answer */}
                <div
                  className={`grid transition-all duration-300 ease-in-out ${
                    isOpen ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"
                  }`}
                >
                  <div className="overflow-hidden">
                    <div className="px-5 pb-5 pl-[4.5rem]">
                      <p className="text-muted-foreground leading-relaxed">{faq.a}</p>
                    </div>
                  </div>
                </div>
              </div>
            )
          })}
        </div>

        {/* Contact CTA */}
        <div className="mt-12 text-center">
          <p className="text-muted-foreground mb-4">Still have questions?</p>
          <a
            href="mailto:support@fvundi.com"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-gradient-to-r from-red-500 to-red-600 text-white font-medium hover:shadow-lg hover:shadow-red-500/25 transition-all duration-300 hover:-translate-y-0.5"
          >
            Contact our team
          </a>
        </div>
      </div>
    </section>
  )
}
